### ISSUE TITLE
Update kiss3d and nalgebra

### ISSUE THREAD

**Issue by taiki-e** [openrr/openrr#104]
It seems kiss3d 0.29 that fixes https://github.com/sebcrozet/kiss3d/issues/262 has been released, but that depends on a new version of nalgebra (0.24). 

https://github.com/openrr/openrr/blob/89cec32e2873d7b2cff075522521895c7b7f8e1d/Cargo.toml#L33-L34

Some dependencies need to be updated first for openrr to switch to kiss 0.29 and nalgebra 0.24.

See #121 for the current status.

**Comment by OTL** [comment]
Let's update!
