### ISSUE TITLE
openrr-gui: joint_position_sender: Depending on how to move slider, response on urdf-viz side is very slow

### ISSUE THREAD

**Issue by taiki-e** [openrr/openrr#108]
This is due to `joint_position_sender` calls `send_joint_positions` every time the slider moves, but I'm not yet very clear how to fix this.

GUI can tell if the user is clicking on the slider, so I think it's maybe a good idea to reduce the frequency of calling `send_joint_positions` while the user is clicking on the slider.

**Comment by taiki-e** [comment]
> GUI can tell if the user is clicking on the slider, so I think it's maybe a good idea to reduce the frequency of calling send_joint_positions while the user is clicking on the slider.


I tried this approach and found that it didn't work well. (https://github.com/taiki-e/openrr/commit/67ff05d22630ad85c4555e3dcb8f88075018ccc6)
The underlying problem seems to be calling the next `send_joint_positions` before the `send_joint_positions` completes, and limiting it may work well.

**Comment by OTL** [comment]
[This change](https://github.com/openrr/openrr/compare/try-to-fix-slow-gui) improves the situation, but i want to dig a bit more about it.

**Comment by OTL** [comment]
I completely understand what is the cause!
