### ISSUE TITLE
ncollide3d became now parry!

### ISSUE THREAD

**Issue by OTL** [openrr/openrr#163]
https://www.dimforge.com/

ncollide3d is maintained, but it does not seem to be upgraded.

We have to consider to migrate to parry. I don't know what is the difference and we can use it actually.

https://github.com/dimforge/parry

**Comment by taiki-e** [comment]
https://dimforge.com/blog/2021/01/29/this-month-in-dimforge/#announcing-parry-010

> Parry is a complete remake of our ncollide crate. It is declined in four crates: parry2d, parry3d, parry2d-f64, parry3d-f64, depending on whether you want, 2D or 3D geometry, and f32 or f64 accuracy. Parry is born from the merge of most of the geometry code we had in Rapier, and some of the geometric code we ported from ncollide.

That blog also has a comparison of Parry and ncollide.

**Comment by taiki-e** [comment]
[As kiss3d depends on ncollide3d](https://github.com/sebcrozet/kiss3d/blob/daf3fd9318ae0903b26cb607132ba92e4e17c70d/src/lib.rs#L151), we probably can't migrate yet.

**Comment by OTL** [comment]
I see. Let's keep ncollide3d for a while. It's not a problem actually.
