### ISSUE TITLE
Implement wav speaker

### ISSUE THREAD

**Issue by OTL** [openrr/openrr#173]
I want a robot speak Japanese or more language, using Speaker trait.

https://github.com/openrr/openrr/blob/main/arci/src/traits/speaker.rs

If there are a  code bellow,

```rust
speaker.speak("move to zero");
```

Say 'こんにちは'.

The struct will be like below

```
struct AudioSpeaker {
  message_to_file_path: HashMap,
}

impl Speaker for AudioSpeaker {
  fn speak(&self, message: &str) {
    if let Some(path) = message_to_file_path(message) {
      play_file(path);
    }
  }
}
```

You can use some libraries like, https://github.com/RustAudio/rodio.

Let's create new crate `arci-speak-audio`.

**Comment by sktometometo** [comment]
Working on https://github.com/openrr/openrr/pull/175
