### ISSUE TITLE
Add licenses in all source files

### ISSUE THREAD

**Issue by OTL** [openrr/openrr#35]

**Comment by taiki-e** [comment]
As far as I know, per-file license notifications are not always necessary. Actually, rust-lang/rust removed it from all files: https://github.com/rust-lang/rust/pull/57108

However, it is preferable that all published crates have a license file. This is required when redistributing crates. See https://github.com/mmastrac/rust-ctor/issues/109 for more.

**Comment by OTL** [comment]
I see, thanks!
I close this issue.
