### ISSUE TITLE
Test Coverage >70% for arci and so on.

### ISSUE THREAD

**Issue by OTL** [openrr/openrr#47]

**Comment by OTL** [comment]
* test_total_condition_fail
* test_total_condition_accessor
* https://codecov.io/gh/openrr/openrr/src/main/arci/src/traits/joint_trajectory_client.rs: new, accessor

* https://codecov.io/gh/openrr/openrr/src/main/openrr-client/src/clients/print_speaker.rs
* https://codecov.io/gh/openrr/openrr/src/main/arci-urdf-viz/src/client.rs

**Comment by a-miyadera** [comment]
@OTL 
すいません、pushできなかったのですが、権限が足りないとかありませんか？

```
$ git push origin tests
ERROR: Permission to openrr/openrr.git denied to a-miyadera.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by OTL** [comment]
I changed the permission. Please retry it!

**Comment by a-miyadera** [comment]
Thank you! It worked.

**Comment by OTL** [comment]
https://github.com/openrr/openrr/tree/main/arci-ros

↓See below as an example.

https://github.com/openrr/openrr/blob/main/arci-ros/tests/test_joy.rs
