### ISSUE TITLE
Robot examples

### ISSUE THREAD

**Issue by bobbbay** [openrr/openrr#603]
Hi all, great crate/s. However, even after reading through the available documentation and examples, I'm still in the dark on how these parts should be put together to create a robot. For example, if I have a wired robot with a library for motor controllers, how do I put combine the `arci`, `ros2`, and `teleop` crates to create a controlled one?

What I'm really asking for is a few examples of all of these crates assembled in different ways. I've searched everywhere but can't find many examples of openrr. I'm definitely missing something :)!

**Comment by OTL** [comment]
Hi, sorry for lacking the documentation　and examples.

If your robot supports ros2 (ros2_control/navigation) interface, you can use arci-ros2, which is optional (and a plugin).
There is only a simple example for turtlebot3.

 If you really want to implement arci, you have to write a plugin like [arci-ros2 plugin](https://github.com/openrr/openrr/blob/main/arci-ros2/src/plugin.rs) for now.

I recommend implementing the standard ros2 interface at first if you are using ros2 already.

Is it possible to give us some more information about your robot to support your situation?

**Comment by bobbbay** [comment]
My robot doesn't support ROS - it's not programmed at all. I would like to run openrr on the on-board processor, teleoperated with a network connection.

After looking into it a little more, I implemented the types that interface with my hardware directly from `arci`. I have yet to figure out how to control it remotely, though. In any case, implementing `arci` traits was what I wanted to do, so I can close this :).
