### ISSUE TITLE
Not sure where to find community for this project.. Is there a matrix channel?

### ISSUE THREAD

**Issue by BikiniBottomsVeryOwn** [openrr/openrr#701]
I would like to learn this/get involved with helping on this project, but I'm unsure where to start and how to communicate with others involved with this project. Is there a matrix channel for this?

**Comment by OTL** [comment]
Thank you for having an interest in OpenRR!!!
We don't have enough docs and a chat system for this project yet. We are preparing some docs actually.

If you want to say something, you can use Issue, as you did.
Are you happy if there are a discord for this project?

**Comment by JafarAbdi** [comment]
I'm also interested in joining a chat system once it exists

> Are you happy if there is a discord for this project?

That would be great to have!

**Comment by OTL** [comment]
I created discord [here](https://discord.gg/EcEpjQxY)!!!

**Comment by OTL** [comment]
I updated the invitation link (without time limit)
https://discord.gg/8DAFFKc88B
