### ISSUE TITLE
send_joint_positions GUI

### ISSUE THREAD

**Issue by OTL** [openrr/openrr#76]
send joint positions from GUI like
http://wiki.ros.org/joint_state_publisher

![image](https://raw.githubusercontent.com/ros/joint_state_publisher/kinetic-devel/joint_state_publisher_gui/screenshot.png)

* Input: urdf file and toml config file
* Output: [JointTrajectoryCline](https://github.com/openrr/openrr/blob/main/arci/src/traits/joint_trajectory_client.rs) send_joint_positions()

* Load urdf file and get `joint names` and `joint limits.`
* Creat Slider bar using the joint names and limits.
* Send joint positions when slider is moved.

`arci-ros` and `arci-urdf-viz` should be used as implementations of `JointTrajectoryClient`.

**Comment by taiki-e** [comment]
(I'm working on this.)
