### ISSUE TITLE
Configurable parameter system

### ISSUE THREAD

**Issue by OTL** [openrr/openrr#78]
toml is simple, and it's great. But sometimes we need more complicated configurable parameter system.

* replace value by argument
* include other toml files from toml file
* overwrite default values by another toml file

We have to use google at first to confirm that there are no system which realize our needs.

**Comment by mitsuharu-kojima** [comment]
https://github.com/toml-lang/toml/issues/36

**Comment by mitsuharu-kojima** [comment]
https://github.com/toml-lang/toml/issues/397

**Comment by OTL** [comment]
I completely agree that TOML should not have such functionality which we need. It must be simple.
